[package]
name = "orientation_display"
version = "0.1.0"
authors = ["Sirius <sirius@x250>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kiss3d = "0.31"
